// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grpc/storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	SizeGb        float64                `protobuf:"fixed64,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_grpc_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateVolumeRequest) GetSizeGb() float64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_grpc_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_storage_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVolumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVolumeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateVolumeResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetsStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetsStatsRequest) Reset() {
	*x = GetsStatsRequest{}
	mi := &file_grpc_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetsStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsStatsRequest) ProtoMessage() {}

func (x *GetsStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsStatsRequest.ProtoReflect.Descriptor instead.
func (*GetsStatsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_storage_proto_rawDescGZIP(), []int{2}
}

type GetsStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalSpaceGb  float64                `protobuf:"fixed64,2,opt,name=total_space_gb,json=totalSpaceGb,proto3" json:"total_space_gb,omitempty"`
	FreeSpaceGb   float64                `protobuf:"fixed64,3,opt,name=free_space_gb,json=freeSpaceGb,proto3" json:"free_space_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetsStatsResponse) Reset() {
	*x = GetsStatsResponse{}
	mi := &file_grpc_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetsStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetsStatsResponse) ProtoMessage() {}

func (x *GetsStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetsStatsResponse.ProtoReflect.Descriptor instead.
func (*GetsStatsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetsStatsResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetsStatsResponse) GetTotalSpaceGb() float64 {
	if x != nil {
		return x.TotalSpaceGb
	}
	return 0
}

func (x *GetsStatsResponse) GetFreeSpaceGb() float64 {
	if x != nil {
		return x.FreeSpaceGb
	}
	return 0
}

var File_grpc_storage_proto protoreflect.FileDescriptor

const file_grpc_storage_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/storage.proto\x12\x02pb\"K\n" +
	"\x13CreateVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x01R\x06sizeGb\"^\n" +
	"\x14CreateVolumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\x12\n" +
	"\x10GetsStatsRequest\"v\n" +
	"\x11GetsStatsResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12$\n" +
	"\x0etotal_space_gb\x18\x02 \x01(\x01R\ftotalSpaceGb\x12\"\n" +
	"\rfree_space_gb\x18\x03 \x01(\x01R\vfreeSpaceGb2\x8c\x01\n" +
	"\x0eStorageService\x12A\n" +
	"\fCreateVolume\x12\x17.pb.CreateVolumeRequest\x1a\x18.pb.CreateVolumeResponse\x127\n" +
	"\bGetStats\x12\x14.pb.GetsStatsRequest\x1a\x15.pb.GetsStatsResponseB&Z$github.com/swe-ayush/nimbusfs/pkg/pbb\x06proto3"

var (
	file_grpc_storage_proto_rawDescOnce sync.Once
	file_grpc_storage_proto_rawDescData []byte
)

func file_grpc_storage_proto_rawDescGZIP() []byte {
	file_grpc_storage_proto_rawDescOnce.Do(func() {
		file_grpc_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_storage_proto_rawDesc), len(file_grpc_storage_proto_rawDesc)))
	})
	return file_grpc_storage_proto_rawDescData
}

var file_grpc_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_storage_proto_goTypes = []any{
	(*CreateVolumeRequest)(nil),  // 0: pb.CreateVolumeRequest
	(*CreateVolumeResponse)(nil), // 1: pb.CreateVolumeResponse
	(*GetsStatsRequest)(nil),     // 2: pb.GetsStatsRequest
	(*GetsStatsResponse)(nil),    // 3: pb.GetsStatsResponse
}
var file_grpc_storage_proto_depIdxs = []int32{
	0, // 0: pb.StorageService.CreateVolume:input_type -> pb.CreateVolumeRequest
	2, // 1: pb.StorageService.GetStats:input_type -> pb.GetsStatsRequest
	1, // 2: pb.StorageService.CreateVolume:output_type -> pb.CreateVolumeResponse
	3, // 3: pb.StorageService.GetStats:output_type -> pb.GetsStatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_storage_proto_init() }
func file_grpc_storage_proto_init() {
	if File_grpc_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_storage_proto_rawDesc), len(file_grpc_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_storage_proto_goTypes,
		DependencyIndexes: file_grpc_storage_proto_depIdxs,
		MessageInfos:      file_grpc_storage_proto_msgTypes,
	}.Build()
	File_grpc_storage_proto = out.File
	file_grpc_storage_proto_goTypes = nil
	file_grpc_storage_proto_depIdxs = nil
}
